на проверку
htmlacademy-htmlcss/2016315-sedona-34 pull request #2
Opened 2022-05-23 18:17 UTC by Ganmii

2022-05-25 08:18 UTC, olga19972010 requested changes
В целом разметка получилась работающая, но нужно ее немного доработать, чтобы она стала еще лучше:).
Основные моменты:
- Обратить внимание как использовать тег списка `<ul>`
- Форматирование кода через Ctrl+Alt+L, и следить чтобы элементы тега не переходили на другие строки, чтобы все выглядело красиво.
- Нэйминг, внимательно смотреть правописание английских слов.
- `<input>` оборачиваем в `<lable>`
- Если мы находимся на странице, то ссылки ссылающиеся на нее будут пустыми.

В комментариях к pull request написаны замечания, которые нужно исправить.
Движемся в правильном направлении!

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +            <a class="navigation-link" href="index.html">
Когда мы находимся на текущей странице, можно на нее не ссылаться. (12, 17 строки)
Почитай про пустой href:  https://up.htmlacademy.ru/htmlcss/34/module/2/item/4/15

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +            <a class="navigation-link" href="about-sedona.html">О Седоне</a>
Страницы "О Седоне" не существует в макете.
В д/з написано как мы ссылаемся(прописываем href) на них: https://up.htmlacademy.ru/htmlcss/34/tasks/4

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +              ><span class="visually-hidden">Понравились</span>
Часть элемента ссылки `a` перенеслась вместе со span и визуально кажется, что `a` не закрыт.(32 и 37 строки)
Хорошо делать так, когда один тег занимает  только одну строку.
https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-01

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +            >
Части одного тега должны быть на одной строке вместе с ним:
`<a>Home</a>`
Только если она очень длинная, следует переносить.
```
<a >
  Home .. и много текста
</a>
```

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +        <h1 class="welcome-city">
Тут будет уместнее использовать заголовок второго уровня. 
h1 - это заголовок описывающий всю страницу, из названия не совсем понятно о чем сайт. И его лучше прописать после `<main>` Как в демке https://up.htmlacademy.ru/htmlcss/34/demos/7433#5

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +      <section class="advantages">
![секции](https://user-images.githubusercontent.com/105501418/170194187-f59c2321-e299-4913-8b19-c334f1e98af2.png)

Ты объеденешь эту секцию все вместе, а потом разделяешь на списки, но если внимательно посмотреть, то можно выделить в этом блоке две самостоятельные секции, у которой есть свой контент. 
Будет уместнее их разделить на разные секции.

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +        <ul
Этот список, из комментария выше, следует выделить в отдельную секцию. Не следует его выделять в список с одним элементом. Тег `<ul> `использовать стоит, когда есть несколько повторяющихся элементов(список товаров, дел).
https://up.htmlacademy.ru/htmlcss/34/module/2/item/3/2

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +        <ul class="advantages-list">
73-98 строчки это все общий список, его не следует дробить на три списка с одним элементом.
```
<ul>
  <li>1</li>
  <li>2</li>
  <li>3</li>
</ul>
```

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +        <ul
100-142 строчки это все общий список, его не следует дробить на четыре списка с одним элементом.

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +            <h2 class="advantages-title">Там есть мост дьявола</h2>
В этом элементе должна быть размечена картинка, она тут контентная. 
![image](https://user-images.githubusercontent.com/105501418/170195561-3b439a23-222e-4c31-8fa5-597c8be69abc.png)

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +        <ul class="interested-list">
Тут самостоятельная секция, тег `<ul>` здесь не уместен.

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +        <p class="subscription-title">Подпишитесь на рассылку</p>
Тут может быть заголовком параграф.

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +      <form action="#" method="post">
Тут отдельная секция "Подпишись на нас", со своим заголовком и параграфом, внутри которой есть форма.

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +      <section class="footer-social">
![image](https://user-images.githubusercontent.com/105501418/170197121-ed2e8d31-1c96-4e7d-9160-94bc8c1edd1f.png)
Это общая секция, в которой есть список телефон и логотип, а не три разных.

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +        <ul class="footer-item">
Тут правильное использование списка, молодец!

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +              ><span class="visually-hidden">Вконтакте</span>
Следи за частями тега, соблюдай единый стиль кодирования.
Тут логотип соцсетей это контентаня картинка, которая обернута в сссылку. Поэтому вместо `<span>` нужно использовать тег `<img  src="#" alt="Вконтакте">`

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +      <section class="phone">
это отдельная ссылка или параграф, не секция.

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +      <section class="compani">
это отдельная ссылка, не секция

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +          class="advantages-list advantages-list-blye advantages-list-blye-left"
в названии класса грамматическая ошибка

2022-05-25 08:18 UTC, olga19972010 commented on catalog.html
> +              href="catalog.html"
Когда мы на текущей странице href не нужно прописывать

2022-05-25 08:18 UTC, olga19972010 commented on index.html
>      <title>HTML Academy: Седона</title>
Тут более подходящим будет название `Главная страница сайта Седона.`

2022-05-25 08:18 UTC, olga19972010 commented on catalog.html
> +          <h2 class="visually-hidden">Список гостиниц с фильтрами</h2>
Этот заголовок относится к секции с формой, более подходящее наименование будет связано с фильтрами, например: "Форма фильтрации гостиниц по параметрам". Придумать свое:)

2022-05-25 08:18 UTC, olga19972010 commented on index.html
> +        <input
Хорошим приемом считается оборачивать тег input лейблом  и его скрывать:
```
    <label class="visually-hidden"> Ваш почта
          <input  type="email" placeholder="Ваш e-mail" name="subscription-email" />
     </label>
```

2022-05-25 08:18 UTC, olga19972010 commented on catalog.html
> +              <legend class="catalog-filter-title">Стоимость, ₽:</legend>
группу отдельную выделил, но забыл написать input для диапазона.
![image](https://user-images.githubusercontent.com/105501418/170203093-544087bb-1b22-4b1d-9294-e905af9f9df8.png)

2022-05-25 08:18 UTC, olga19972010 commented on catalog.html
> +        <section class="sorting">
148-163 строки, это отдельная секция с фильтрами.

2022-05-25 08:18 UTC, olga19972010 commented on catalog.html
> +          <div class="product-card">
Далее идет секция со списками карточек. Тут будет уместен тег списка.
Картчки товара хорошо оборачивать в тег `<article>`

2022-05-25 08:18 UTC, olga19972010 commented on catalog.html
> +            <img src="" alt="Рейтинг" />
![секции](https://user-images.githubusercontent.com/105501418/170210185-7cb2f950-72c5-450f-b67d-f46d283ef4c3.png)
В рейтинге тут два элемента, текст с описанием рейтинга и сами звезды, их можно сделать с помощью списка картинок.

2022-05-25 08:18 UTC, olga19972010 commented on catalog.html
> +            </a>
![image](https://user-images.githubusercontent.com/105501418/170211057-f52c1be9-2d00-47b1-be7b-b9fa377d219e.png)
Объясни, не понимаю, для чего добавлять эту ссылку? В макете ее нет.
255-289 строки относиться к `<main> а не <footer>`

2022-05-25 08:18 UTC, olga19972010 commented on catalog.html
> +      <header class="inner-header">
Не корректное использование тега `<header>` внутри` <main>` когда он оборачивает весь `<main>`.
Если хочется выделеить `<header>` то он должен заканчиваться не в конце страницы.

2022-05-25 08:18 UTC, olga19972010 commented on catalog.html
> +    <footer class="page-footer">
Правки в блоке` <footer>` аналогичные, что и на странице index

2022-05-25 17:35 UTC, Ganmii commented on index.html
> +            <a class="navigation-link" href="index.html">
Fixed

2022-05-25 17:35 UTC, Ganmii commented on index.html
> +            <a class="navigation-link" href="about-sedona.html">О Седоне</a>
Fixed

2022-05-25 17:36 UTC, Ganmii commented on index.html
> +              ><span class="visually-hidden">Понравились</span>
Fixed

2022-05-25 17:36 UTC, Ganmii commented on index.html
> +            >
Fixed

2022-05-25 17:42 UTC, Ganmii commented on index.html
> +        <h1 class="welcome-city">
Fixed

2022-05-25 20:44 UTC, Ganmii commented on index.html
> +      <section class="advantages">
Fixed

2022-05-25 20:45 UTC, Ganmii commented on index.html
> +        <ul
Fixed

2022-05-25 20:45 UTC, Ganmii commented on index.html
> +        <ul class="advantages-list">
Fixed

2022-05-25 20:45 UTC, Ganmii commented on index.html
> +        <ul
Fixed

2022-05-25 20:45 UTC, Ganmii commented on index.html
> +            <h2 class="advantages-title">Там есть мост дьявола</h2>
Fixed

2022-05-25 20:56 UTC, Ganmii commented on index.html
> +        <ul class="interested-list">
Fixed

2022-05-25 20:57 UTC, Ganmii commented on index.html
> +        <p class="subscription-title">Подпишитесь на рассылку</p>
Fixed

2022-05-25 21:00 UTC, Ganmii commented on index.html
> +      <form action="#" method="post">
Fixed

2022-05-25 21:00 UTC, Ganmii commented on index.html
> +      <section class="footer-social">
Fixed

2022-05-25 21:00 UTC, Ganmii commented on index.html
> +        <ul class="footer-item">
Fixed

2022-05-25 21:11 UTC, Ganmii commented on index.html
> +              ><span class="visually-hidden">Вконтакте</span>
Fixed

2022-05-25 21:12 UTC, Ganmii commented on index.html
> +      <section class="phone">
Fixed

2022-05-25 21:12 UTC, Ganmii commented on index.html
> +      <section class="compani">
Fixed

2022-05-25 21:13 UTC, Ganmii commented on index.html
> +          class="advantages-list advantages-list-blye advantages-list-blye-left"
Fixed

2022-05-25 21:17 UTC, Ganmii commented on catalog.html
> +              href="catalog.html"
Fixed

2022-05-25 21:17 UTC, Ganmii commented on index.html
>      <title>HTML Academy: Седона</title>
Fixed

2022-05-25 22:02 UTC, Ganmii commented on catalog.html
> +          <h2 class="visually-hidden">Список гостиниц с фильтрами</h2>
Fixed

2022-05-25 22:29 UTC, Ganmii commented on catalog.html
> +              <legend class="catalog-filter-title">Стоимость, ₽:</legend>
Fixed

2022-05-25 23:07 UTC, Ganmii commented on catalog.html
> +    <footer class="page-footer">
Fixed

2022-05-25 23:07 UTC, Ganmii commented on catalog.html
> +      <header class="inner-header">
Fixed

2022-05-25 23:07 UTC, Ganmii commented on catalog.html
> +            </a>
Fixed

2022-05-26 18:23 UTC, Ganmii commented on catalog.html
> +            <img src="" alt="Рейтинг" />
Fixed

2022-05-26 18:23 UTC, Ganmii commented on catalog.html
> +          <div class="product-card">
Fixed

2022-05-30 05:16 UTC, merged